
services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 3

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    restart: unless-stopped
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    expose:
      - "9000"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f php-fpm || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/lib/html
    networks:
      - inception_network
    ports:
      - "443:443"

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      device: /home/vmaelatmi/data/mariadb_data
      o: bind
      type: none

  wordpress_data:
    driver: local
    driver_opts:
      device: /home/vmaelatmi/data/wordpress_data
      o: bind
      type: none

networks:
  inception_network:
    name: inception
    driver: bridge